(define (pascal n)
	(define (cal-number x y)
		(cond ((= x 1) 1)
					((= y 1) 1)
					((= x y) 1)
					(else (+ (cal-number (- x 1) (- y 1)) (cal-number x (- y 1))))
		)
	)
	(define (pascal-line now total)
		(define (display-line-internal now total)
			(display (cal-number now total))
			(cond ((< now total) (display-line-internal (+ now 1) total))
			)
		)
		(display-line-internal 1 now)
		(display "\n")
		(cond ((< now total) (pascal-line (+ now 1) total)))
	)
	(pascal-line 1 n)
)
(pascal 5)